theme = "dracula"
icons = "awesome"
[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# 

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
# format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

# [[block]]
# block = "cpu"
# interval = 1
# 
[[block]]
block = "load"
interval = 1
format = "{1m}"


# [[block]]
# block = "sound"

[[block]]
block = "backlight"
# minimum = 15
# maximum = 100
# cycle = [100, 50, 0, 50]

# 
# [[block]]
# block = "battery"
# interval = 10
# format = "{percentage} {time}"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"


# [[block]]
# block = "custom"
# command = "echo \uf011" # assumes fontawesome icons
# # on_click = "pkexec `echo -e 'suspend\npoweroff\nreboot' | rofi`"
# on_click = "suspend\npoweroff\nreboot | dmenu"
# interval = "once"

[[block]]
block = "net"
device = "wlp6s0"
# format = "{ssid} {signal_strength} {ip} {speed_down;K*B} {speed_up;K*B}" 
format = " {speed_down;K*B} {speed_up;K*B}" 



[[block]]
block = "networkmanager"
on_click = "~/.local/bin/rofi-wifi-menu.sh"
# on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid} {strength}"

[[block]]
block = "time"
# on_click = 'notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")"'
on_click = 'notify-send "$(cal)"'
interval = 60
format = "%a %d/%b %I:%M"

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
format = " {layout}"
interval = 1

[[block]]
block = "sound"
on_click = "alacritty -e alsamixer"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
on_click = "~/.config/i3/scripts/shutdown_menu -p rofi -c;"
interval = "once"
